### ISSUE TITLE
Websocket API fails with no such table candles

### ISSUE THREAD

**Issue by alexlipa91** [bitfinexcom/bfx-hf-data-server#19]
#### Issue type
- [ ] bug

  ```bfx:hf:data-server` error processing message: Error: ER_NO_SUCH_TABLE: Table 'mydb.candles' doesn't exist```

#### Brief description
I am trying to use this module `bfx-hf-strategy-py` with the dataserver running on another port. I want to use the sql backend for it. I properly set up the connection (it succeeds) but at the first invocation of the WS API it complains that the table doesn't exist.

How do I create such table? Am I missing something?

#### Steps to reproduce
run the example in `bfx-hf-strategy-py` using the dataserver as backend

**Comment by ph4z** [comment]
I had to manually create these tables too.
Here you can find some kind of description of the tables: https://github.com/bitfinexcom/bfx-hf-models-adapter-sql/tree/master/migrations.

**Comment by robertkowalski** [comment]
https://github.com/bitfinexcom/bfx-hf-strategy-py supports `exe.with_local_database()` now, which will use a local sqlite database for syncing candle values.

 in the long term the candle functionality for `bfx-hf-data-server` is going to get removed. the sqlite support in bfx-hf-strategy-py should support many millions of records and just runs out of the box and is a good replacement for caching larger amounts of candles
